/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stock_management_gui;

import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.MySql;
import order_management_gui.kitchen_gui.KitchenDashboard;

/**
 *
 * @author sanja
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
        loadOrdersTable();
    }

    private void loadOrdersTable() {

        try {

            // Clear the existing table data
            DefaultTableModel model = (DefaultTableModel) OrdersView.getModel();

            model.setRowCount(0);

            // Fetch the data from the database
            String query = "SELECT * FROM order_details";

            ResultSet rs = MySql.executeSearch(query);

            // Iterate through the ResultSet
            while (rs.next()) {

                // Fetch employee details from the ResultSet
                String Order_ID = rs.getString("order_id");

                // Add a new row with EmpID, fullName, current date, and a placeholder for current time
                model.addRow(new Object[]{Order_ID});

            }

        } catch (Exception e) {

            e.printStackTrace();

        }

    }

    private void loadOrderItems() {

        String orderId = orderIdField.getText().trim();

        if (orderId.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Please enter an Order ID.");

            return;

        }

        DefaultTableModel model = (DefaultTableModel) OrdersView.getModel();

        model.setRowCount(0);

        double total = 0;

        try {

            ResultSet rs = MySql.executeSearch("SELECT * FROM order_details "
                    + "INNER JOIN order_items ON order_details.order_id = order_items.order_details_order_id "
                    + "INNER JOIN portion_types ON portion_types.portion_types_id = order_items.portion_types_portion_types_id "
                    + "INNER JOIN foods ON order_items.foods_food_id = foods.food_id WHERE order_details.order_id = '" + orderId + "'");

            while (rs.next()) {

                double price = rs.getDouble("price");

                model.addRow(new Object[]{rs.getString("order_id"), rs.getString("foods.food_name"), rs.getString("portion_types.portion_types_name"), rs.getInt("order_qty"), rs.getDouble("price")});

                total += price;
            }

            TotalTextField.setText(String.valueOf(total));

        } catch (Exception ex) {

            ex.printStackTrace();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        EmpID = new javax.swing.JLabel();
        orderIdField = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        BodyPanel = new javax.swing.JPanel();
        SelectOrdersPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SalesCountLable = new javax.swing.JLabel();
        SaleseCount = new javax.swing.JTextField();
        kButton1 = new com.k33ptoo.components.KButton();
        OrderViewPanel = new javax.swing.JPanel();
        AddProductTextField = new javax.swing.JTextField();
        AddProductLable = new javax.swing.JLabel();
        QTYTextField = new javax.swing.JTextField();
        QTYLable = new javax.swing.JLabel();
        AddButton = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrdersView = new javax.swing.JTable();
        TotalLable = new javax.swing.JLabel();
        TotalTextField = new javax.swing.JTextField();
        BackToDashboardButton = new javax.swing.JButton();
        kButton3 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        HeaderPanel.setPreferredSize(new java.awt.Dimension(540, 80));

        EmpID.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        EmpID.setText("Enter Order ID / Mobile Number : ");

        orderIdField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        orderIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderIdFieldActionPerformed(evt);
            }
        });
        orderIdField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                orderIdFieldKeyReleased(evt);
            }
        });

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/refresh.png"))); // NOI18N
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(EmpID)
                .addGap(12, 12, 12)
                .addComponent(orderIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(refreshButton)
                .addGap(36, 36, 36))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(EmpID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        getContentPane().add(HeaderPanel, java.awt.BorderLayout.PAGE_START);

        BodyPanel.setLayout(new java.awt.BorderLayout());

        SelectOrdersPanel.setPreferredSize(new java.awt.Dimension(614, 40));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        SalesCountLable.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        SalesCountLable.setText("To Day Sales Count :");

        SaleseCount.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        SaleseCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleseCountActionPerformed(evt);
            }
        });

        kButton1.setText("Check Kitchen");
        kButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton1.setkEndColor(new java.awt.Color(0, 204, 204));
        kButton1.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kButton1.setkPressedColor(new java.awt.Color(0, 102, 153));
        kButton1.setkSelectedColor(new java.awt.Color(0, 102, 153));
        kButton1.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton1MouseClicked(evt);
            }
        });
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectOrdersPanelLayout = new javax.swing.GroupLayout(SelectOrdersPanel);
        SelectOrdersPanel.setLayout(SelectOrdersPanelLayout);
        SelectOrdersPanelLayout.setHorizontalGroup(
            SelectOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectOrdersPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218)
                .addComponent(SalesCountLable)
                .addGap(12, 12, 12)
                .addComponent(SaleseCount, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        SelectOrdersPanelLayout.setVerticalGroup(
            SelectOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectOrdersPanelLayout.createSequentialGroup()
                .addGroup(SelectOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectOrdersPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(SelectOrdersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SelectOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SelectOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(SalesCountLable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SaleseCount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BodyPanel.add(SelectOrdersPanel, java.awt.BorderLayout.PAGE_START);

        AddProductTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        AddProductTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductTextFieldActionPerformed(evt);
            }
        });

        AddProductLable.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        AddProductLable.setText("Add New Product : ");

        QTYTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        QTYTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QTYTextFieldActionPerformed(evt);
            }
        });

        QTYLable.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        QTYLable.setText("QTY : ");

        AddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N

        OrdersView.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        OrdersView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Items Name", "Portion", "QTY", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OrdersView.getTableHeader().setReorderingAllowed(false);
        OrdersView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(OrdersView);

        TotalLable.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        TotalLable.setText("Total :");

        TotalTextField.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        TotalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTextFieldActionPerformed(evt);
            }
        });

        BackToDashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back-arrow.png"))); // NOI18N
        BackToDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToDashboardButtonActionPerformed(evt);
            }
        });

        kButton3.setText("Pay");
        kButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton3.setkEndColor(new java.awt.Color(0, 204, 204));
        kButton3.setkHoverEndColor(new java.awt.Color(0, 102, 153));
        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton3.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kButton3.setkPressedColor(new java.awt.Color(0, 102, 153));
        kButton3.setkSelectedColor(new java.awt.Color(0, 102, 153));
        kButton3.setkStartColor(new java.awt.Color(0, 102, 153));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OrderViewPanelLayout = new javax.swing.GroupLayout(OrderViewPanel);
        OrderViewPanel.setLayout(OrderViewPanelLayout);
        OrderViewPanelLayout.setHorizontalGroup(
            OrderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderViewPanelLayout.createSequentialGroup()
                .addGroup(OrderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OrderViewPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(OrderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                            .addGroup(OrderViewPanelLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(AddProductLable)
                                .addGap(12, 12, 12)
                                .addComponent(AddProductTextField)
                                .addGap(18, 18, 18)
                                .addComponent(QTYLable)
                                .addGap(12, 12, 12)
                                .addComponent(QTYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(AddButton))))
                    .addGroup(OrderViewPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TotalLable)
                        .addGap(12, 12, 12)
                        .addGroup(OrderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TotalTextField)
                            .addComponent(kButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
            .addGroup(OrderViewPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackToDashboardButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OrderViewPanelLayout.setVerticalGroup(
            OrderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrderViewPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(OrderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OrderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AddProductLable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddProductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(QTYLable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(QTYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(OrderViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(BackToDashboardButton)
                .addGap(7, 7, 7))
        );

        BodyPanel.add(OrderViewPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(BodyPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void orderIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderIdFieldActionPerformed

        loadOrderItems();

    }//GEN-LAST:event_orderIdFieldActionPerformed

    private void AddProductTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddProductTextFieldActionPerformed

    private void QTYTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QTYTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QTYTextFieldActionPerformed

    private void TotalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalTextFieldActionPerformed

    private void BackToDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToDashboardButtonActionPerformed

//       LogOut Button
        System.exit(0);

    }//GEN-LAST:event_BackToDashboardButtonActionPerformed

    private void SaleseCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleseCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaleseCountActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed

        PriceView p_view = new PriceView(this, true); // `true` -> Modal

        p_view.setTotalPrice(TotalTextField.getText()); // Total price eka set karanawa

        p_view.setVisible(true);
        
        

    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton1MouseClicked


    }//GEN-LAST:event_kButton1MouseClicked

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed

        KitchenDashboard kitchenDashboard = new KitchenDashboard();

        kitchenDashboard.setVisible(true);

    }//GEN-LAST:event_kButton1ActionPerformed

    DefaultTableModel model;

    public void search(String orderid) {

        model = (DefaultTableModel) OrdersView.getModel();

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);

        OrdersView.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(orderid, 0));

    }

    private void orderIdFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_orderIdFieldKeyReleased

        String Od_ID = orderIdField.getText();

        search(Od_ID);


    }//GEN-LAST:event_orderIdFieldKeyReleased

    private void OrdersViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersViewMouseClicked

        if (evt.getClickCount() == 2) {

            int row = OrdersView.getSelectedRow();

            if (row != -1) {

                String Orderid = String.valueOf(OrdersView.getValueAt(row, 0));

                orderIdField.setText(Orderid);

                loadOrderItems();

            }

        }

    }//GEN-LAST:event_OrdersViewMouseClicked

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed

        reset();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void reset() {

        orderIdField.setText("");

        model = (DefaultTableModel) OrdersView.getModel();

        model.setRowCount(0);

        loadOrdersTable();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddButton;
    private javax.swing.JLabel AddProductLable;
    private javax.swing.JTextField AddProductTextField;
    private javax.swing.JButton BackToDashboardButton;
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JLabel EmpID;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel OrderViewPanel;
    private javax.swing.JTable OrdersView;
    private javax.swing.JLabel QTYLable;
    private javax.swing.JTextField QTYTextField;
    private javax.swing.JLabel SalesCountLable;
    private javax.swing.JTextField SaleseCount;
    private javax.swing.JPanel SelectOrdersPanel;
    private javax.swing.JLabel TotalLable;
    private javax.swing.JTextField TotalTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton3;
    private javax.swing.JTextField orderIdField;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
