/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finance_department_gui;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.formdev.flatlaf.util.SwingUtils;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author GOLDEN FIELD
 */
public class FinanceDepartmentDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FinanceDepartmentDashboard
     */
    public FinanceDepartmentDashboard() {
        initComponents();
    }

    public void changeimage(JLabel image, String resourceImage) {

        ImageIcon imageIcon = new ImageIcon(getClass().getResource(resourceImage));
        image.setIcon(imageIcon);

    }

    boolean hide = true;

    public void hidemenu(JPanel showmenu, boolean dashboard, JLabel icButton) {

        if (dashboard == true) {

            showmenu.setPreferredSize(new Dimension(60, showmenu.getHeight()));
            changeimage(icButton, "/resources/menu.png");
        } else {

            showmenu.setPreferredSize(new Dimension(300, showmenu.getHeight()));
            changeimage(icButton, "/resources/back-arrow.png");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sideBarMainPanel = new com.k33ptoo.components.KGradientPanel();
        sideBarIconPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        SideBarButtonPanel = new javax.swing.JPanel();
        incomeManageButton = new com.k33ptoo.components.KButton();
        companyPromotionButton = new com.k33ptoo.components.KButton();
        productPromotionButton = new com.k33ptoo.components.KButton();
        addExpencesButton = new com.k33ptoo.components.KButton();
        payrollManagementButton = new com.k33ptoo.components.KButton();
        MainDashboardPanel = new javax.swing.JPanel();
        FooterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        HeaderPanel.setBackground(new java.awt.Color(153, 153, 153));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(638, 50));

        jLabel1.setFont(new java.awt.Font("Audiowide", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addGap(281, 281, 281))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(HeaderPanel, java.awt.BorderLayout.PAGE_START);

        sideBarMainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sideBarMainPanel.setkEndColor(new java.awt.Color(0, 0, 0));
        sideBarMainPanel.setkStartColor(new java.awt.Color(255, 255, 255));
        sideBarMainPanel.setPreferredSize(new java.awt.Dimension(300, 551));
        sideBarMainPanel.setLayout(new java.awt.BorderLayout());

        sideBarIconPanel.setBackground(new java.awt.Color(153, 153, 153));
        sideBarIconPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sideBarIconPanel.setPreferredSize(new java.awt.Dimension(60, 549));
        sideBarIconPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back-arrow.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);

        sideBarIconPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        sideBarIconPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 60, 10));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, java.awt.BorderLayout.CENTER);

        sideBarIconPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 60, 60));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        sideBarIconPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 60, -1));

        sideBarMainPanel.add(sideBarIconPanel, java.awt.BorderLayout.LINE_START);

        SideBarButtonPanel.setPreferredSize(new java.awt.Dimension(240, 549));
        SideBarButtonPanel.setLayout(new java.awt.GridLayout(13, 1, 6, 6));

        incomeManageButton.setText("Income Management");
        incomeManageButton.setAlignmentY(0.0F);
        incomeManageButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        incomeManageButton.setkBorderRadius(0);
        incomeManageButton.setkEndColor(new java.awt.Color(51, 51, 51));
        incomeManageButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        incomeManageButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        incomeManageButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        incomeManageButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        incomeManageButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        incomeManageButton.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(incomeManageButton);

        companyPromotionButton.setText("Company Promotion");
        companyPromotionButton.setAlignmentY(0.0F);
        companyPromotionButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        companyPromotionButton.setkBorderRadius(0);
        companyPromotionButton.setkEndColor(new java.awt.Color(51, 51, 51));
        companyPromotionButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        companyPromotionButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        companyPromotionButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        companyPromotionButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        companyPromotionButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        companyPromotionButton.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(companyPromotionButton);

        productPromotionButton.setText("Product Promotion");
        productPromotionButton.setAlignmentY(0.0F);
        productPromotionButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productPromotionButton.setkBorderRadius(0);
        productPromotionButton.setkEndColor(new java.awt.Color(51, 51, 51));
        productPromotionButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        productPromotionButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        productPromotionButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        productPromotionButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        productPromotionButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        productPromotionButton.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(productPromotionButton);

        addExpencesButton.setText("Add Expences");
        addExpencesButton.setAlignmentY(0.0F);
        addExpencesButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addExpencesButton.setkBorderRadius(0);
        addExpencesButton.setkEndColor(new java.awt.Color(51, 51, 51));
        addExpencesButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        addExpencesButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        addExpencesButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        addExpencesButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        addExpencesButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        addExpencesButton.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(addExpencesButton);

        payrollManagementButton.setText("Payroll Management");
        payrollManagementButton.setAlignmentY(0.0F);
        payrollManagementButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        payrollManagementButton.setkBorderRadius(0);
        payrollManagementButton.setkEndColor(new java.awt.Color(51, 51, 51));
        payrollManagementButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        payrollManagementButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        payrollManagementButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        payrollManagementButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        payrollManagementButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        payrollManagementButton.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(payrollManagementButton);

        sideBarMainPanel.add(SideBarButtonPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(sideBarMainPanel, java.awt.BorderLayout.LINE_START);

        FooterPanel.setBackground(new java.awt.Color(51, 51, 51));
        FooterPanel.setPreferredSize(new java.awt.Dimension(747, 60));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("All Rights Reserved | NeoLife Software Solutions");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Designed & Developed By NeoLife Software Solutions");

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterPanelLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(211, 211, 211))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainDashboardPanelLayout = new javax.swing.GroupLayout(MainDashboardPanel);
        MainDashboardPanel.setLayout(MainDashboardPanelLayout);
        MainDashboardPanelLayout.setHorizontalGroup(
            MainDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FooterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
        );
        MainDashboardPanelLayout.setVerticalGroup(
            MainDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainDashboardPanelLayout.createSequentialGroup()
                .addGap(0, 468, Short.MAX_VALUE)
                .addComponent(FooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(MainDashboardPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
       
          if (hide == true) {

            hidemenu(sideBarMainPanel, hide,jLabel4);
            SwingUtilities.updateComponentTreeUI(this);

            hide = false;

        } else {

            hidemenu(sideBarMainPanel, hide,jLabel4);
            SwingUtilities.updateComponentTreeUI(this);

            hide = true;

        }
    }//GEN-LAST:event_jLabel4MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinanceDepartmentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel MainDashboardPanel;
    private javax.swing.JPanel SideBarButtonPanel;
    private com.k33ptoo.components.KButton addExpencesButton;
    private com.k33ptoo.components.KButton companyPromotionButton;
    private com.k33ptoo.components.KButton incomeManageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.k33ptoo.components.KButton payrollManagementButton;
    private com.k33ptoo.components.KButton productPromotionButton;
    private javax.swing.JPanel sideBarIconPanel;
    private com.k33ptoo.components.KGradientPanel sideBarMainPanel;
    // End of variables declaration//GEN-END:variables
}
