/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr_department_gui;

import finance_department_gui.*;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import com.formdev.flatlaf.util.SwingUtils;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author GOLDEN FIELD
 */
public class HRDepartmentDashboard extends javax.swing.JFrame {

    /**
     * Creates new form FinanceDepartmentDashboard
     */
    public HRDepartmentDashboard() {
        initComponents();
    }

    public void changeimage(JLabel image, String resourceImage) {

        ImageIcon imageIcon = new ImageIcon(getClass().getResource(resourceImage));
        image.setIcon(imageIcon);

    }

    boolean hide = true;

    public void hidemenu(JPanel showmenu, boolean dashboard, JLabel icButton) {

        if (dashboard == true) {

            showmenu.setPreferredSize(new Dimension(60, showmenu.getHeight()));
            changeimage(icButton, "/resources/menu.png");
        } else {

            showmenu.setPreferredSize(new Dimension(300, showmenu.getHeight()));
            changeimage(icButton, "/resources/back-arrow.png");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sideBarMainPanel = new com.k33ptoo.components.KGradientPanel();
        sideBarIconPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        SideBarButtonPanel = new javax.swing.JPanel();
        addEmployeeButton = new com.k33ptoo.components.KButton();
        addDepartmentButton = new com.k33ptoo.components.KButton();
        productPromotionButton = new com.k33ptoo.components.KButton();
        addEmployeeToDepartmentButton = new com.k33ptoo.components.KButton();
        addNewUserButton = new com.k33ptoo.components.KButton();
        manageEmployeeButton = new com.k33ptoo.components.KButton();
        manageEmployeeAddressButton = new com.k33ptoo.components.KButton();
        leaveManageButton = new com.k33ptoo.components.KButton();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton5 = new com.k33ptoo.components.KButton();
        kButton6 = new com.k33ptoo.components.KButton();
        kButton7 = new com.k33ptoo.components.KButton();
        kButton8 = new com.k33ptoo.components.KButton();
        kButton9 = new com.k33ptoo.components.KButton();
        kButton10 = new com.k33ptoo.components.KButton();
        kButton11 = new com.k33ptoo.components.KButton();
        kButton12 = new com.k33ptoo.components.KButton();
        MainDashboardPanel = new javax.swing.JPanel();
        FooterPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        HeaderPanel.setBackground(new java.awt.Color(153, 153, 153));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(638, 50));

        jLabel1.setFont(new java.awt.Font("Audiowide", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                .addGap(281, 281, 281))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(HeaderPanel, java.awt.BorderLayout.PAGE_START);

        sideBarMainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sideBarMainPanel.setkEndColor(new java.awt.Color(0, 0, 0));
        sideBarMainPanel.setkStartColor(new java.awt.Color(255, 255, 255));
        sideBarMainPanel.setPreferredSize(new java.awt.Dimension(300, 551));
        sideBarMainPanel.setLayout(new java.awt.BorderLayout());

        sideBarIconPanel.setBackground(new java.awt.Color(153, 153, 153));
        sideBarIconPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sideBarIconPanel.setPreferredSize(new java.awt.Dimension(60, 549));
        sideBarIconPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back-arrow.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);

        sideBarIconPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        sideBarIconPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 60, 10));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, java.awt.BorderLayout.CENTER);

        sideBarIconPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 60, 60));

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        sideBarIconPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 60, -1));

        sideBarMainPanel.add(sideBarIconPanel, java.awt.BorderLayout.LINE_START);

        SideBarButtonPanel.setPreferredSize(new java.awt.Dimension(240, 549));
        SideBarButtonPanel.setLayout(new java.awt.GridLayout(17, 1, 6, 6));

        addEmployeeButton.setText("Add Employee");
        addEmployeeButton.setAlignmentY(0.0F);
        addEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addEmployeeButton.setkBorderRadius(0);
        addEmployeeButton.setkEndColor(new java.awt.Color(51, 51, 51));
        addEmployeeButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        addEmployeeButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        addEmployeeButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        addEmployeeButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        addEmployeeButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        addEmployeeButton.setkStartColor(new java.awt.Color(153, 153, 153));
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });
        SideBarButtonPanel.add(addEmployeeButton);

        addDepartmentButton.setText("Add Department");
        addDepartmentButton.setAlignmentY(0.0F);
        addDepartmentButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addDepartmentButton.setkBorderRadius(0);
        addDepartmentButton.setkEndColor(new java.awt.Color(51, 51, 51));
        addDepartmentButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        addDepartmentButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        addDepartmentButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        addDepartmentButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        addDepartmentButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        addDepartmentButton.setkStartColor(new java.awt.Color(153, 153, 153));
        addDepartmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepartmentButtonActionPerformed(evt);
            }
        });
        SideBarButtonPanel.add(addDepartmentButton);

        productPromotionButton.setText("Employee Position");
        productPromotionButton.setAlignmentY(0.0F);
        productPromotionButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productPromotionButton.setkBorderRadius(0);
        productPromotionButton.setkEndColor(new java.awt.Color(51, 51, 51));
        productPromotionButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        productPromotionButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        productPromotionButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        productPromotionButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        productPromotionButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        productPromotionButton.setkStartColor(new java.awt.Color(153, 153, 153));
        productPromotionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productPromotionButtonActionPerformed(evt);
            }
        });
        SideBarButtonPanel.add(productPromotionButton);

        addEmployeeToDepartmentButton.setText("Add Employee to Department");
        addEmployeeToDepartmentButton.setAlignmentY(0.0F);
        addEmployeeToDepartmentButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addEmployeeToDepartmentButton.setkBorderRadius(0);
        addEmployeeToDepartmentButton.setkEndColor(new java.awt.Color(51, 51, 51));
        addEmployeeToDepartmentButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        addEmployeeToDepartmentButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        addEmployeeToDepartmentButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        addEmployeeToDepartmentButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        addEmployeeToDepartmentButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        addEmployeeToDepartmentButton.setkStartColor(new java.awt.Color(153, 153, 153));
        addEmployeeToDepartmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeToDepartmentButtonActionPerformed(evt);
            }
        });
        SideBarButtonPanel.add(addEmployeeToDepartmentButton);

        addNewUserButton.setText("Add New User");
        addNewUserButton.setAlignmentY(0.0F);
        addNewUserButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addNewUserButton.setkBorderRadius(0);
        addNewUserButton.setkEndColor(new java.awt.Color(51, 51, 51));
        addNewUserButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        addNewUserButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        addNewUserButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        addNewUserButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        addNewUserButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        addNewUserButton.setkStartColor(new java.awt.Color(153, 153, 153));
        addNewUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewUserButtonActionPerformed(evt);
            }
        });
        SideBarButtonPanel.add(addNewUserButton);

        manageEmployeeButton.setText("Manage Employee");
        manageEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageEmployeeButton.setkBorderRadius(0);
        manageEmployeeButton.setkEndColor(new java.awt.Color(51, 51, 51));
        manageEmployeeButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        manageEmployeeButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        manageEmployeeButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        manageEmployeeButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        manageEmployeeButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        manageEmployeeButton.setkStartColor(new java.awt.Color(153, 153, 153));
        manageEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeButtonActionPerformed(evt);
            }
        });
        SideBarButtonPanel.add(manageEmployeeButton);

        manageEmployeeAddressButton.setText("Manage Employee Address");
        manageEmployeeAddressButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageEmployeeAddressButton.setkBorderRadius(0);
        manageEmployeeAddressButton.setkEndColor(new java.awt.Color(51, 51, 51));
        manageEmployeeAddressButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        manageEmployeeAddressButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        manageEmployeeAddressButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        manageEmployeeAddressButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        manageEmployeeAddressButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        manageEmployeeAddressButton.setkStartColor(new java.awt.Color(153, 153, 153));
        manageEmployeeAddressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeAddressButtonActionPerformed(evt);
            }
        });
        SideBarButtonPanel.add(manageEmployeeAddressButton);

        leaveManageButton.setText("Leave Manage");
        leaveManageButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        leaveManageButton.setkBorderRadius(0);
        leaveManageButton.setkEndColor(new java.awt.Color(51, 51, 51));
        leaveManageButton.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        leaveManageButton.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        leaveManageButton.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        leaveManageButton.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        leaveManageButton.setkPressedColor(new java.awt.Color(51, 51, 51));
        leaveManageButton.setkStartColor(new java.awt.Color(153, 153, 153));
        leaveManageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveManageButtonActionPerformed(evt);
            }
        });
        SideBarButtonPanel.add(leaveManageButton);

        kButton4.setText("Mark Attendance");
        kButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton4.setkBorderRadius(0);
        kButton4.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton4.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton4.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        kButton4.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton4.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        kButton4.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton4.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(kButton4);

        kButton5.setText("Payroll Integration");
        kButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton5.setkBorderRadius(0);
        kButton5.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton5.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton5.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        kButton5.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton5.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        kButton5.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton5.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(kButton5);

        kButton6.setText("Add Advanced Payroll");
        kButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton6.setkBorderRadius(0);
        kButton6.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton6.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton6.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        kButton6.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton6.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        kButton6.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton6.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(kButton6);

        kButton7.setText("Manage Customer");
        kButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton7.setkBorderRadius(0);
        kButton7.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton7.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton7.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        kButton7.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton7.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        kButton7.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton7.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(kButton7);

        kButton8.setText("Add New Company");
        kButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton8.setkBorderRadius(0);
        kButton8.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton8.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton8.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        kButton8.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton8.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        kButton8.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton8.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(kButton8);

        kButton9.setText("Add New Supplier");
        kButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton9.setkBorderRadius(0);
        kButton9.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton9.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton9.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        kButton9.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton9.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        kButton9.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton9.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(kButton9);

        kButton10.setText("Delivery Guy Register");
        kButton10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton10.setkBorderRadius(0);
        kButton10.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton10.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton10.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        kButton10.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton10.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        kButton10.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton10.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(kButton10);

        kButton11.setText("Delivery Vehical Register");
        kButton11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton11.setkBorderRadius(0);
        kButton11.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton11.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton11.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        kButton11.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton11.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton11.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(kButton11);

        kButton12.setText("Delivery Attendance");
        kButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton12.setkBorderRadius(0);
        kButton12.setkEndColor(new java.awt.Color(51, 51, 51));
        kButton12.setkHoverEndColor(new java.awt.Color(153, 153, 153));
        kButton12.setkHoverForeGround(new java.awt.Color(204, 204, 204));
        kButton12.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton12.setkIndicatorColor(new java.awt.Color(204, 0, 51));
        kButton12.setkPressedColor(new java.awt.Color(51, 51, 51));
        kButton12.setkStartColor(new java.awt.Color(153, 153, 153));
        SideBarButtonPanel.add(kButton12);

        sideBarMainPanel.add(SideBarButtonPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(sideBarMainPanel, java.awt.BorderLayout.LINE_START);

        FooterPanel.setBackground(new java.awt.Color(51, 51, 51));
        FooterPanel.setPreferredSize(new java.awt.Dimension(747, 60));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("All Rights Reserved | NeoLife Software Solutions");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Designed & Developed By NeoLife Software Solutions");

        javax.swing.GroupLayout FooterPanelLayout = new javax.swing.GroupLayout(FooterPanel);
        FooterPanel.setLayout(FooterPanelLayout);
        FooterPanelLayout.setHorizontalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FooterPanelLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(211, 211, 211))
        );
        FooterPanelLayout.setVerticalGroup(
            FooterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout MainDashboardPanelLayout = new javax.swing.GroupLayout(MainDashboardPanel);
        MainDashboardPanel.setLayout(MainDashboardPanelLayout);
        MainDashboardPanelLayout.setHorizontalGroup(
            MainDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FooterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 886, Short.MAX_VALUE)
        );
        MainDashboardPanelLayout.setVerticalGroup(
            MainDashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainDashboardPanelLayout.createSequentialGroup()
                .addGap(0, 422, Short.MAX_VALUE)
                .addComponent(FooterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(MainDashboardPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed

        if (hide == true) {

            hidemenu(sideBarMainPanel, hide, jLabel4);
            SwingUtilities.updateComponentTreeUI(this);

            hide = false;

        } else {

            hidemenu(sideBarMainPanel, hide, jLabel4);
            SwingUtilities.updateComponentTreeUI(this);

            hide = true;

        }
    }//GEN-LAST:event_jLabel4MousePressed

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeButtonActionPerformed

        AddEmployee employee = new AddEmployee();
        employee.setVisible(true);

    }//GEN-LAST:event_addEmployeeButtonActionPerformed

    private void addDepartmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepartmentButtonActionPerformed

        AddDepartment department = new AddDepartment();
        department.setVisible(true);

    }//GEN-LAST:event_addDepartmentButtonActionPerformed

    private void productPromotionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productPromotionButtonActionPerformed
        EmployeePosition position = new EmployeePosition();
        position.setVisible(true);

    }//GEN-LAST:event_productPromotionButtonActionPerformed

    private void addEmployeeToDepartmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeToDepartmentButtonActionPerformed
        AddEmployeeToDepartments department = new AddEmployeeToDepartments();
        department.setVisible(true);

    }//GEN-LAST:event_addEmployeeToDepartmentButtonActionPerformed

    private void addNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserButtonActionPerformed
        AddNewUser user = new AddNewUser();
        user.setVisible(true);
    }//GEN-LAST:event_addNewUserButtonActionPerformed

    private void manageEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeButtonActionPerformed
        ManageEmployee employee = new ManageEmployee();
        employee.setVisible(true);
    }//GEN-LAST:event_manageEmployeeButtonActionPerformed

    private void manageEmployeeAddressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeAddressButtonActionPerformed
        ManageEmployeeAddress employeeAddress = new ManageEmployeeAddress();
        employeeAddress.setVisible(true);
    }//GEN-LAST:event_manageEmployeeAddressButtonActionPerformed

    private void leaveManageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveManageButtonActionPerformed
        LeaveManage leave = new LeaveManage();
        leave.setVisible(true);
    }//GEN-LAST:event_leaveManageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRDepartmentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FooterPanel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel MainDashboardPanel;
    private javax.swing.JPanel SideBarButtonPanel;
    private com.k33ptoo.components.KButton addDepartmentButton;
    private com.k33ptoo.components.KButton addEmployeeButton;
    private com.k33ptoo.components.KButton addEmployeeToDepartmentButton;
    private com.k33ptoo.components.KButton addNewUserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.k33ptoo.components.KButton kButton10;
    private com.k33ptoo.components.KButton kButton11;
    private com.k33ptoo.components.KButton kButton12;
    private com.k33ptoo.components.KButton kButton4;
    private com.k33ptoo.components.KButton kButton5;
    private com.k33ptoo.components.KButton kButton6;
    private com.k33ptoo.components.KButton kButton7;
    private com.k33ptoo.components.KButton kButton8;
    private com.k33ptoo.components.KButton kButton9;
    private com.k33ptoo.components.KButton leaveManageButton;
    private com.k33ptoo.components.KButton manageEmployeeAddressButton;
    private com.k33ptoo.components.KButton manageEmployeeButton;
    private com.k33ptoo.components.KButton productPromotionButton;
    private javax.swing.JPanel sideBarIconPanel;
    private com.k33ptoo.components.KGradientPanel sideBarMainPanel;
    // End of variables declaration//GEN-END:variables
}
